// components/Expenditure/BasicDetailsSection.jsx
import InputField from "../Forms/InputField";
import SelectField from "../Forms/SelectField";
import DateField from "../Forms/DateField";
import { getFinancialYears } from "../../hooks/useFinancialYear";

const financialYearOptions = getFinancialYears(2023).map((fy) => ({
  label: fy,
  value: fy,
}));

const monthOptions = [
  { label: "Select Month", value: "" },
  { label: "January", value: "01" },
  { label: "February", value: "02" },
  { label: "March", value: "03" },
  { label: "April", value: "04" },
  { label: "May", value: "05" },
  { label: "June", value: "06" },
  { label: "July", value: "07" },
  { label: "August", value: "08" },
  { label: "September", value: "09" },
  { label: "October", value: "10" },
  { label: "November", value: "11" },
  { label: "December", value: "12" },
];

const BasicDetailsSection = ({
  register,
  departments,
  ddos,
  grants,
  isExpenditureLoading,
  watch,
}) => {
  const financialYear = watch("financialYear");
  const selectedMonth = watch("month");

  let minDate = "";
  let maxDate = "";

  if (financialYear && selectedMonth) {
    const [startYear, endYear] = financialYear.split("-");

    // Jan-Mar belongs to endYear
    const year =
      Number(selectedMonth) >= 1 && Number(selectedMonth) <= 3
        ? endYear
        : startYear;

    const lastDay = new Date(year, selectedMonth, 0).getDate();

    minDate = `${year}-${selectedMonth}-01`;
    maxDate = `${year}-${selectedMonth}-${lastDay}`;
  }
  return (
    <>
      <SelectField
        label="Select Sector"
        name="sector"
        register={register}
        required
        options={[
          { label: "Select Sector", value: "" },
          { label: "01-COUNCIL", value: "COUNCIL" },
          { label: "02-STATE", value: "STATE" },
        ]}
      />

      <InputField
        label="Voucher No"
        name="voucherNo"
        register={register}
        readonly
        helperText="( Auto generated by system )"
        placeholder={isExpenditureLoading ? "fetching..." : ""}
      />

      <SelectField
        label="Financial Year"
        name="financialYear"
        register={register}
        options={[
          { label: "Select Financial Year", value: "" },
          ...financialYearOptions,
        ]}
      />
      <SelectField
        label="Month"
        name="month"
        register={register}
        options={monthOptions}
      />
      <DateField
        label="Date"
        name="voucherDate"
        register={register}
        min={minDate}
        max={maxDate}
      />

      <InputField
        label="Requisition No"
        name="requisitionNo"
        register={register}
      />

      <DateField
        label="Requisition Date"
        name="requisitionDate"
        register={register}
        min={minDate}
        max={maxDate}
      />

      <SelectField
        label="Grant Name & No"
        name="grantNo"
        register={register}
        options={[{ label: "Select Grant", value: "" }, ...grants]}
      />

      <SelectField
        label="Department Name & Code"
        name="department"
        register={register}
        options={[{ label: "Select Department", value: "" }, ...departments]}
      />

      <SelectField
        label="Select DDO"
        name="ddo"
        register={register}
        options={[{ label: "Select DDO", value: "" }, ...ddos]}
      />
    </>
  );
};

export default BasicDetailsSection;
