// components/Expenditure/BasicDetailsSection.jsx
import InputField from "../Forms/InputField";
import SelectField from "../Forms/SelectField";
import DateField from "../Forms/DateField";

const BasicDetailsSection = ({
  register,
  departments,
  ddos,
  grants,
  isExpenditureLoading,
}) => {
  return (
    <>
      <SelectField
        label="Select Sector"
        name="sector"
        register={register}
        required
        options={[
          { label: "Select Sector", value: "" },
          { label: "01-COUNCIL", value: "COUNCIL" },
          { label: "02-STATE", value: "STATE" },
        ]}
      />

      <InputField
        label="Voucher No"
        name="voucherNo"
        register={register}
        readonly
        helperText="( Auto generated by system )"
        placeholder={isExpenditureLoading ? "fetching..." : ""}
      />

      <DateField label="Date" name="voucherDate" register={register} />

      <InputField
        label="Requisition No"
        name="requisitionNo"
        register={register}
      />

      <DateField
        label="Requisition Date"
        name="requisitionDate"
        register={register}
      />

      <SelectField
        label="Grant Name & No"
        name="grantNo"
        register={register}
        options={[{ label: "Select Grant", value: "" }, ...grants]}
      />

      <SelectField
        label="Department Name & Code"
        name="department"
        register={register}
        options={[{ label: "Select Department", value: "" }, ...departments]}
      />

      <SelectField
        label="Select DDO"
        name="ddo"
        register={register}
        options={[{ label: "Select DDO", value: "" }, ...ddos]}
      />
    </>
  );
};

export default BasicDetailsSection;
