import { useState } from "react";
import { useForm } from "react-hook-form";
import FormWrapper from "../../components/Forms/FormWrapper";
import InputField from "../../components/Forms/InputField";
import SelectField from "../../components/Forms/SelectField";
import TextAreaField from "../../components/Forms/TextAreaField";
import DateField from "../../components/Forms/DateField";
import { rupeesToWords } from "../../utils/rupeesToWords";
import { formatIndianNumber } from "../../utils/formatIndianCurrency";
import Breadcrumbs from "../../components/ui/Breadcrumbs";
import { useEffect } from "react";
import { getGeneratedChallanNo } from "../../api/autoChallan.api.js";
import { useDepartments } from "../../hooks/useDepartments.js";
import { useDivisions } from "../../hooks/useDivisions.js";
import { useDdo } from "../../hooks/useDDO.js";


const Challan = () => {
  const [isChallanLoading, setIsChallanLoading] = useState(true);
  const { departments, loading: isDepartmentLoading } = useDepartments({
    type: "COUNCIL",
  });

  const { divisions, loading: isDivisionLoading } = useDivisions();
  const { ddos, loading: isDdoLoading } = useDdo();

  const {
    register,
    handleSubmit,
    watch,
    setValue,
    formState: { errors, isSubmitting },
  } = useForm({
    defaultValues: {
      challanType: "",
      department: "",
      divisionCode: "",
      ddo: "",
      majorHead: "",
      subMajorHead: "",
      subSubMajorHead: "",
      minorHead: "",
      detailHead: "",
      treasuryName: "",
      treasuryChallanNo: "",
      treasuryChallanDate: "",
      totalAmount: "",
      amountInWords: "",
      remarks: "",
    },
  });

  // Auto convert amount to words
  const totalAmount = watch("totalAmount");

  useEffect(() => {
    if (!totalAmount) return;

    const raw = totalAmount.replace(/,/g, "");
    setValue("totalAmount", formatIndianNumber(raw), { shouldValidate: true });
    setValue("amountInWords", rupeesToWords(raw), { shouldValidate: true });
  }, [totalAmount, setValue]);

  // fetching challan no
  useEffect(() => {
    const fetchNextChallanNo = async () => {
      setIsChallanLoading(true);

      try {
        const res = await getGeneratedChallanNo("COUNCIL");

        setValue("challanNo", res.data.challanNo, {
          shouldDirty: false,
          shouldValidate: false,
        });
      } catch (error) {
        console.error("Failed to fetch challan number", error);
        setValue("challanNo", "ERROR");
      } finally {
        setIsChallanLoading(false);
      }
    };

    fetchNextChallanNo();
  }, [setValue]);

  //submit
  const onSubmit = async (data) => {
    const payload = {
      challanType: data.challanType,
      departmentId: Number(data.department),
      divisionId: Number(data.divisionCode),
      ddoId: Number(data.ddo),
      majorHead: data.majorHead,
      subMajorHead: data.subMajorHead,
      subSubMajorHead: data.subSubMajorHead,
      minorHead: data.minorHead,
      detailHead: data.detailHead,
      treasuryCode: data.treasuryName,
      treasuryChallanNo: data.treasuryChallanNo,
      treasuryChallanDate: data.treasuryChallanDate,
      amount: data.totalAmount.replace(/,/g, ""),
      remarks: data.remarks,
    };

    const res = await fetch("/api/challan", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!res.ok) {
      alert("Failed to create challan");
      return;
    }

    const result = await res.json();
    alert(`Challan created successfully\nChallan No: ${result.challanNo}`);
  };

  return (
    <div className="min-h-screen w-full px-5 py-3 pb-6">
      <div className="border-b border-zinc-400 leading-9">
        <Breadcrumbs
          items={[
            { label: "Dashboard", path: "/" },
            { label: "Challan", path: "/challan" },
            { label: "Create Challan", path: "/challan" },
          ]}
        />

        <h1 className="font-unbounded">Fill Challan Details :</h1>
      </div>

      <FormWrapper onSubmit={handleSubmit(onSubmit)}>
        <InputField
          label="Counterfoil No."
          helperText="(in case of receipt in cash by the Cashier)"
          name="counterfoilNo"
          register={register}
        />

        <DateField
          label="Counterfoil Date"
          name="counterfoilDate"
          register={register}
          readonly={true}
        />

        <InputField
          label="Challan No."
          readonly={true}
          helperText="( Auto-generated by system )"
          name="challanNo"
          register={register}
          placeholder={isChallanLoading ? "fetching..." : ""}
        />

        <DateField
          label="Challan Date"
          name="challanDate"
          register={register}
        />

        <SelectField
          label="Type"
          name="challanType"
          register={register}
          removable
          options={[
            { label: "01-Council", value: "council" },
            // { label: "02-CSS", value: "css" },
          ]}
        />

        <SelectField
          label="Department"
          name="department"
          register={register}
          options={departments}
          disabled={isDepartmentLoading}
        />

        <SelectField
          label="Division Code"
          name="divisionCode"
          register={register}
          options={divisions}
          disabled={isDivisionLoading}
        />

        <SelectField
          label="DDO"
          name="ddo"
          register={register}
          removable
          options={ddos}
          disabled={isDdoLoading}
        />

        <SelectField
          label="Major Head"
          name="majorHead"
          register={register}
          removable
          options={[
            { label: "01-Council", value: "council" },
            { label: "02-CSS", value: "css" },
          ]}
        />

        <SelectField
          label="Sub Major Head"
          name="subMajorHead"
          register={register}
          removable
          options={[
            { label: "01-Council", value: "council" },
            { label: "02-CSS", value: "css" },
          ]}
        />

        <SelectField
          label="Sub Sub Major Head"
          name="subSubMajorHead"
          register={register}
          removable
          options={[
            { label: "01-Council", value: "council" },
            { label: "02-CSS", value: "css" },
          ]}
        />

        <SelectField
          label="Minor Head"
          name="minorHead"
          register={register}
          removable
          options={[
            { label: "01-Council", value: "council" },
            { label: "02-CSS", value: "css" },
          ]}
        />

        <SelectField
          label="Detail Head"
          name="detailHead"
          register={register}
          removable
          options={[
            { label: "01-Council", value: "council" },
            { label: "02-CSS", value: "css" },
          ]}
        />

        <SelectField
          label="Treasury Name"
          name="treasuryName"
          register={register}
          removable
          options={[
            { label: "01-Council", value: "council" },
            { label: "02-CSS", value: "css" },
          ]}
        />

        <InputField
          label="Treasury Challan No"
          name="treasuryChallanNo"
          register={register}
        />

        <DateField
          label="Treasury Challan Date"
          name="treasuryChallanDate"
          register={register}
        />

        <InputField
          label="Total Amount"
          name="totalAmount"
          register={register}
        />

        <InputField
          label="Amount In Words"
          name="amountInWords"
          register={register}
          readonly={true}
        />

        <TextAreaField label="Remarks" name="remarks" register={register} />
      </FormWrapper>
    </div>
  );
};

export default Challan;
